language: java

addons:
  sonarcloud:
    organization: "freakey17-github"
    token: $SONAR_TOKEN8

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
branches:
  only:
    - master
